### ISSUE TITLE
Update gitter references to relevant discord channels 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/doc.common#11]
All products now have channels on the Consensys discord rather than gitter.  The 404 and footer templates include gitter.

**Comment by NicolasMassart** [comment]
@MadelineMurray can you paste the channel invite links here please?
Be careful to have permanent invites activated.

**Comment by MadelineMurray** [comment]
Teku - https://discord.gg/9mCVSY6
Orion - https://discord.gg/n8m22JK
EthSigner - https://discord.gg/5U9Jwp7
Eth2Signer - https://discord.gg/EA7WGzA
