### ISSUE TITLE
Update contributing guides around inclusive language

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/doc.common#6]
Update contributing guide around inclusive language:

https://developers.google.com/style/word-list#blacklist

This change will probably be completed before the software changes are finished so include a note saying we're in the process of updating existing occurrences.

**Comment by NicolasMassart** [comment]
See https://github.com/PegaSysEng/doc.common/wiki/Pegasys-Documentation-Style-Guide#5-be-inclusive
